tap "homebrew/bundle"
tap "homebrew/services"
tap "ryu0118/dgraph"
brew "borgbackup"
brew "borgmatic"
brew "btop"
brew "docker"
brew "dotnet"
brew "dpkg"
brew "dune"
brew "fakeroot"
brew "git"
brew "gradle"
brew "inetutils"
brew "jq"
brew "libftdi"
brew "libimobiledevice"
brew "mas"
brew "minicom"
brew "neovim"
brew "nethack"
brew "ocaml"
brew "opam"
brew "openjdk@17"
brew "pacvim"
brew "php", restart_service: :changed
brew "picocom"
brew "pipx"
brew "qemu"
brew "speedtest-cli"
brew "starship"
brew "strongswan"
brew "tldr"
brew "tmux"
brew "wimlib"
cask "arc"
cask "arduino-ide"
cask "detexify"
cask "dotnet-runtime"
cask "forklift"
cask "google-drive"
cask "intellij-idea-ce"
cask "knockknock"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "nextcloud"
cask "obsidian"
cask "raspberry-pi-imager"
cask "rectangle"
cask "ultimaker-cura"
cask "visual-studio-code"
cask "zoom"
cask "zulip"
mas "AusweisApp", id: 948660805
mas "Battery Monitor", id: 836505650
mas "Bitwarden", id: 1352778147
mas "CHM Reader - Enjoy", id: 1661528239
mas "HEIC Converter", id: 1294126402
mas "HP Smart", id: 1474276998
mas "HTTPBot", id: 1232603544
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "OneDrive", id: 823766827
mas "PL2303Serial", id: 1624835354
mas "Strongbox", id: 897283731
mas "Symbols", id: 1612933742
mas "Tailscale", id: 1475387142
mas "TestFlight", id: 899247664
mas "Usage", id: 1561788435
mas "WhatsApp", id: 310633997
mas "Windows App", id: 1295203466
mas "Xcode", id: 497799835
vscode "asvetliakov.vscode-neovim"
vscode "bierner.markdown-mermaid"
vscode "emmanuelbeziat.vscode-great-icons"
vscode "formulahendry.dotnet-test-explorer"
vscode "franneck94.c-cpp-runner"
vscode "hansampfaall.dimacs"
vscode "janisdd.vscode-edit-csv"
vscode "llvm-vs-code-extensions.lldb-dap"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-ceintl.vscode-language-pack-de"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.dotnet-maui"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vsliveshare.vsliveshare"
vscode "ocamllabs.ocaml-platform"
vscode "redhat.java"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "tomoki1207.pdf"
vscode "twxs.cmake"
vscode "vadimcn.vscode-lldb"
vscode "vintharas.learn-vim"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "wavetrace.wavetrace"
vscode "zxh404.vscode-proto3"
