source_directories:
    - /Users/manuelselch/Documents
    - /Users/manuelselch/Library/Preferences/Nextcloud/nextcloud.cfg


repositories:
    - path: ssh://borgwarehouse@100.94.179.34:2222/./01073503
      label: backupserver

one_file_system: true

compression: lz4
archive_name_format: 'backup-{now}'

keep_daily: 7
keep_monthly: 4
keep_yearly: 1

read_special: true